"""Add reservation type as enum

Revision ID: 0b135827e5d6
Revises: ce51866da32d
Create Date: 2024-07-08 01:18:23.192258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b135827e5d6'
down_revision: Union[str, None] = 'ce51866da32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

reservationtype_enum = sa.Enum(
    'EXAM', 'MEETING', 'EVENT', 'OTHER', name='reservationtype')


def upgrade() -> None:
    reservationtype_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'type',
                    existing_type=sa.VARCHAR(),
                    type_=reservationtype_enum,
                    existing_nullable=False,
                    postgresql_using='type::text::reservationtype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'type',
                    existing_type=reservationtype_enum,
                    type_=sa.VARCHAR(),
                    existing_nullable=False,
                    postgresql_using='type::text::reservationtype')
    # ### end Alembic commands ###

    reservationtype_enum.drop(op.get_bind(), checkfirst=True)
