"""Update Reservation and Solicitation Title, Reason Fields

Revision ID: 12f1cc7e68b4
Revises: bf27d37bbe93
Create Date: 2024-09-15 18:31:28.072292

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "12f1cc7e68b4"
down_revision: str | None = "bf27d37bbe93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classroomsolicitation",
        sa.Column(
            "reservation_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )

    op.execute(
        "UPDATE classroomsolicitation SET reservation_title = 'Sem título' WHERE reservation_title IS NULL"
    )
    op.alter_column("classroomsolicitation", "reservation_title", nullable=False)

    op.alter_column(
        "classroomsolicitation", "reason", existing_type=sa.VARCHAR(), nullable=True
    )

    op.alter_column("reservation", "name", new_column_name="title")
    op.alter_column("reservation", "description", new_column_name="reason")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        "UPDATE classroomsolicitation SET reason = 'Sem motivo' WHERE reason IS NULL"
    )
    op.alter_column(
        "classroomsolicitation", "reason", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("classroomsolicitation", "reservation_title")

    op.alter_column("reservation", "title", new_column_name="name")
    op.alter_column("reservation", "reason", new_column_name="description")
