"""teste crawl

Revision ID: 13e28d818266
Revises: ce51866da32d
Create Date: 2024-07-09 12:44:18.638479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13e28d818266'
down_revision: Union[str, None] = 'ce51866da32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classroom', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('classroom', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_classroom_building_id', table_name='classroom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_classroom_building_id', 'classroom', ['building_id'], unique=False)
    op.alter_column('classroom', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classroom', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
