"""Rename group boolean flag

Revision ID: 17397e462799
Revises: a572377bd0c6
Create Date: 2025-05-01 14:56:39.218832

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17397e462799"
down_revision: str | None = "a572377bd0c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("main", sa.Boolean(), nullable=True))
    op.execute('UPDATE "group" SET main = TRUE WHERE complete = TRUE')
    op.execute('UPDATE "group" SET main = FALSE WHERE main IS NULL')
    op.alter_column("group", "main", nullable=False)
    op.drop_column("group", "complete")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column("complete", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute('UPDATE "group" SET complete = TRUE WHERE main = TRUE')
    op.execute('UPDATE "group" SET complete = FALSE WHERE complete IS NULL')
    op.alter_column("group", "complete", nullable=False)
    op.drop_column("group", "main")
    # ### end Alembic commands ###
