"""add codcur and codhab to curriculum

Revision ID: 2c6d478b880e
Revises: bf8387c71371
Create Date: 2026-05-27 22:57:20.206436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c6d478b880e'
down_revision: Union[str, None] = 'bf8387c71371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # adiciona como nullable temporariamente
    op.add_column(
        'curriculum',
        sa.Column('codcur', sa.Integer(), nullable=True)
    )

    op.add_column(
        'curriculum',
        sa.Column('codhab', sa.Integer(), nullable=True)
    )

    # preenche registros antigos
    op.execute("""
        UPDATE curriculum
        SET codcur = id,
            codhab = 0
        WHERE codcur IS NULL
    """)

    # agora pode tornar NOT NULL
    op.alter_column('curriculum', 'codcur', nullable=False)
    op.alter_column('curriculum', 'codhab', nullable=False)

    # constraint composta
    op.create_unique_constraint(
        'uq_curriculum_codcur_codhab',
        'curriculum',
        ['codcur', 'codhab']
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_curriculum_codcur_codhab', 'curriculum', type_='unique')
    op.drop_column('curriculum', 'codhab')
    op.drop_column('curriculum', 'codcur')
    # ### end Alembic commands ###
