"""Create api access log and api incident report feature

Revision ID: 2ea02fbd7b52
Revises: 5e270fe67556
Create Date: 2026-08-25 00:25:19.513063

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2ea02fbd7b52"
down_revision: str | None = "5e270fe67556"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apiaccesslog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "security_level",
            sa.Enum(
                "PUBLIC",
                "AUTHENTICATED",
                "RESTRICTED",
                "ADMIN",
                "UNKNOWN",
                name="apisecuritylevel",
            ),
            nullable=False,
        ),
        sa.Column("endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apiaccesslog_status_code"), "apiaccesslog", ["status_code"], unique=False
    )
    op.create_index(
        op.f("ix_apiaccesslog_timestamp"), "apiaccesslog", ["timestamp"], unique=False
    )
    op.create_table(
        "apiincidentreport",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="incidentreportlevel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "INVESTIGATING", "RESOLVED", name="incidentreportstatus"
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("access_log_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["access_log_id"], ["apiaccesslog.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apiincidentreport_status"), "apiincidentreport", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apiincidentreport_status"), table_name="apiincidentreport")
    op.drop_table("apiincidentreport")
    op.drop_index(op.f("ix_apiaccesslog_timestamp"), table_name="apiaccesslog")
    op.drop_index(op.f("ix_apiaccesslog_status_code"), table_name="apiaccesslog")
    op.drop_table("apiaccesslog")
    sa.Enum(name="incidentreportstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="incidentreportlevel").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="apisecuritylevel").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
