"""Remove group abbreviation

Revision ID: 4773a5364d80
Revises: 1fbd399024e2
Create Date: 2025-04-16 19:54:51.232843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4773a5364d80"
down_revision: Union[str, None] = "1fbd399024e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=True)
    op.drop_column("group", "abbreviation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column(
            "abbreviation", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_group_name"), table_name="group")
    # ### end Alembic commands ###
