"""forum_post_filter_tags

Revision ID: 49bd2f582a5a
Revises: d4cdecd00183
Create Date: 2024-11-11 23:14:07.086646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "49bd2f582a5a"
down_revision: Union[str, None] = "d4cdecd00183"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forumpost", sa.Column("filter_tags", sa.Integer(), nullable=True))
    op.execute("UPDATE forumpost SET filter_tags=1")
    op.alter_column("forumpost", "filter_tags", nullable=False)

    op.execute("UPDATE forumpost SET likes_count=0 WHERE likes_count IS NULL")
    op.alter_column(
        "forumpost", "likes_count", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "forumpost", "likes_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("forumpost", "filter_tags")
    # ### end Alembic commands ###
