"""remove cognito_id

Revision ID: 4abbc03d3542
Revises: 57a9e9d23571
Create Date: 2024-10-21 10:20:36.125454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4abbc03d3542'
down_revision: Union[str, None] = '57a9e9d23571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cognito_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cognito_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
