"""Update Subject and Class models

Revision ID: 4beb4f0ff6d7
Revises: 78a13f742e39
Create Date: 2025-04-01 16:22:01.502562

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4beb4f0ff6d7"
down_revision: str | None = "78a13f742e39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("class", "subscribers")
    op.drop_column("class", "pendings")
    op.drop_column("subject", "activation")
    op.drop_column("subject", "deactivation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subject",
        sa.Column("deactivation", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "subject",
        sa.Column("activation", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "class",
        sa.Column("pendings", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "class",
        sa.Column("subscribers", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
