"""Add unique constraint for group

Revision ID: 4c483339ad7b
Revises: 17397e462799
Create Date: 2025-05-01 17:29:03.342677

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4c483339ad7b"
down_revision: str | None = "17397e462799"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_group_name_for_building", "group", ["building_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_group_name_for_building", "group", type_="unique")

    # ### end Alembic commands ###
