"""Add closed_by in solicitation

Revision ID: 54e3d0a077de
Revises: 12f1cc7e68b4
Create Date: 2024-09-15 19:50:44.965266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "54e3d0a077de"
down_revision: Union[str, None] = "12f1cc7e68b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classroomsolicitation",
        sa.Column("closed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classroomsolicitation", "closed_by")
    # ### end Alembic commands ###
