"""Descrição da mudança

Revision ID: 58b58cda3fb5
Revises: 17c43c8b9acf
Create Date: 2024-06-20 22:03:01.304729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58b58cda3fb5'
down_revision: Union[str, None] = '17c43c8b9acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'skip_exceptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('skip_exceptions', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
