"""classroom_observation

Revision ID: 5c09edeeacb7
Revises: 523faed7a43e
Create Date: 2025-06-26 19:43:36.384259

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5c09edeeacb7"
down_revision: str | None = "523faed7a43e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classroom",
        sa.Column("observation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.execute("UPDATE classroom SET observation = '' WHERE observation IS NULL")
    op.alter_column(
        "classroom",
        "observation",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classroom", "observation")
    # ### end Alembic commands ###
