"""add unique curriculum description per course

Revision ID: 5e270fe67556
Revises: 2c6d478b880e
Create Date: 2026-05-28 16:33:27.772978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e270fe67556'
down_revision: Union[str, None] = '2c6d478b880e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_curriculum_course_description', 'curriculum', ['course_id', 'description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_curriculum_course_description', 'curriculum', type_='unique')
    # ### end Alembic commands ###
