"""Update classroom relations

Revision ID: 6dcd458a20fc
Revises: 4ab489110583
Create Date: 2024-07-27 15:45:23.074719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dcd458a20fc'
down_revision: Union[str, None] = '4ab489110583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservation_classroom_id', table_name='reservation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reservation_classroom_id', 'reservation', ['classroom_id'], unique=False)
    # ### end Alembic commands ###
