"""Add holiday name and update relations

Revision ID: 7daf9b3545d4
Revises: 6dcd458a20fc
Create Date: 2024-07-28 18:30:13.920509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7daf9b3545d4'
down_revision: Union[str, None] = '6dcd458a20fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classroom', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classroom', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('holiday', sa.Column('name', sa.String(), nullable=False, server_default='Padrão'))
    # ### end Alembic commands ###

    # Atualizar todas as linhas existentes para ter o valor padrão
    op.execute("UPDATE holiday SET name = 'Padrão' WHERE name IS NULL")

    # Remover o valor padrão do banco de dados após a migração inicial
    op.alter_column('holiday', 'name', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holiday', 'name')
    op.alter_column('classroom', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('classroom', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
