"""add course structure

Revision ID: 7ec757e08e00
Revises: f53cd44becac
Create Date: 2026-02-03 19:02:16.557778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7ec757e08e00"
down_revision: Union[str, None] = "f53cd44becac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("minimal_duration", sa.Integer(), nullable=False),
        sa.Column("ideal_duration", sa.Integer(), nullable=False),
        sa.Column("maximal_duration", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "period",
            sa.Enum(
                "MORNING", "AFTERNOON", "EVENING", "INTEGRAL", name="course_period_type"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "emphasis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "name", name="unique_emphasis_name_for_course"
        ),
    )
    op.create_table(
        "curriculum",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("emphasis_id", sa.Integer(), nullable=True),
        sa.Column("required_class_hours", sa.Integer(), nullable=False),
        sa.Column("required_work_hours", sa.Integer(), nullable=False),
        sa.Column("optional_free_class_hours", sa.Integer(), nullable=False),
        sa.Column("optional_free_work_hours", sa.Integer(), nullable=False),
        sa.Column("optional_elective_class_hours", sa.Integer(), nullable=False),
        sa.Column("optional_elective_work_hours", sa.Integer(), nullable=False),
        sa.Column("AAC", sa.Integer(), nullable=False),
        sa.Column("AEX", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["emphasis_id"],
            ["emphasis.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "curriculumsubject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("curriculum_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SEMESTRAL", "QUADRIMESTER", name="curriculum_subject_type"),
            nullable=False,
        ),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["curriculum_id"],
            ["curriculum.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "curriculum_id", "subject_id", name="unique_subject_for_curriculum"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("curriculumsubject")
    op.drop_table("curriculum")
    op.drop_table("emphasis")
    op.drop_table("course")
    op.execute("DROP TYPE IF EXISTS curriculum_subject_type")
    op.execute("DROP TYPE IF EXISTS course_period_type")
    # ### end Alembic commands ###
