"""Add year field to calendar and category

Revision ID: 80b726fb19b9
Revises: 557af0c2f159
Create Date: 2025-05-22 14:26:15.000310

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80b726fb19b9"
down_revision: str | None = "557af0c2f159"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calendar", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column("holidaycategory", sa.Column("year", sa.Integer(), nullable=True))
    op.alter_column(
        "occurrence", "schedule_id", existing_type=sa.INTEGER(), nullable=False
    )

    op.execute("UPDATE calendar SET year = 2025 where year IS NULL")
    op.execute("UPDATE holidaycategory SET year = 2025 where year IS NULL")

    op.alter_column("calendar", "year", nullable=False)
    op.alter_column("holidaycategory", "year", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "occurrence", "schedule_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("holidaycategory", "year")
    op.drop_column("calendar", "year")
    # ### end Alembic commands ###
