"""Remove ignore to allocate on classroom

Revision ID: 86626d7aaeee
Revises: 4c483339ad7b
Create Date: 2025-05-01 19:22:41.909218

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86626d7aaeee"
down_revision: str | None = "4c483339ad7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classroom", "ignore_to_allocate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classroom",
        sa.Column(
            "ignore_to_allocate", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        "UPDATE classroom SET ignore_to_allocate = false WHERE ignore_to_allocate IS NULL"
    )
    op.alter_column(
        "classroom",
        "ignore_to_allocate",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###
