"""Add ReservationType in ClassroomSolicitation Table

Revision ID: 875c5b480b66
Revises: f6ee6f6a6ef5
Create Date: 2024-09-05 18:51:21.394856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '875c5b480b66'
down_revision: Union[str, None] = 'f6ee6f6a6ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroomsolicitation', sa.Column('reservation_type', sa.Enum('EXAM', 'MEETING', 'EVENT', 'OTHER', name='reservationtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroomsolicitation', 'reservation_type')
    # ### end Alembic commands ###
