"""Add reason column to classroom solicitation

Revision ID: 884e87702934
Revises: d2e304905247
Create Date: 2024-09-05 06:41:44.541375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "884e87702934"
down_revision: Union[str, None] = "d2e304905247"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classroomsolicitation",
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classroomsolicitation", "reason")
    # ### end Alembic commands ###
