"""edit course structure

Revision ID: 8e2d0a854903
Revises: 7ec757e08e00
Create Date: 2026-02-10 11:55:54.127473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e2d0a854903'
down_revision: Union[str, None] = '7ec757e08e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('curriculum_emphasis_id_fkey'), 'curriculum', type_='foreignkey')
    op.drop_column('curriculum', 'emphasis_id')
    op.drop_table('emphasis')
    op.add_column('curriculum', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('curriculum', 'required_class_hours')
    op.drop_column('curriculum', 'optional_elective_work_hours')
    op.drop_column('curriculum', 'optional_free_work_hours')
    op.drop_column('curriculum', 'required_work_hours')
    op.drop_column('curriculum', 'optional_free_class_hours')
    op.drop_column('curriculum', 'optional_elective_class_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum', sa.Column('optional_elective_class_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('curriculum', sa.Column('optional_free_class_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('curriculum', sa.Column('required_work_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('curriculum', sa.Column('optional_free_work_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('curriculum', sa.Column('optional_elective_work_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('curriculum', sa.Column('required_class_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('curriculum', 'description')
    op.create_table('emphasis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('emphasis_course_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('emphasis_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('emphasis_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('emphasis_pkey')),
    sa.UniqueConstraint('course_id', 'name', name=op.f('unique_emphasis_name_for_course'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.add_column('curriculum', sa.Column('emphasis_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('curriculum_emphasis_id_fkey'), 'curriculum', 'emphasis', ['emphasis_id'], ['id'])
    # ### end Alembic commands ###
