"""Create conclift table

Revision ID: 95fa8f156290
Revises: 24c87e94bf2a
Create Date: 2025-04-25 15:11:52.186319

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95fa8f156290"
down_revision: str | None = "24c87e94bf2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conflict",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("classroom_id", sa.Integer(), nullable=False),
        sa.Column("fist_occurrence_id", sa.Integer(), nullable=False),
        sa.Column("second_occurrence_id", sa.Integer(), nullable=False),
        sa.Column("first_schedule_id", sa.Integer(), nullable=False),
        sa.Column("second_schedule_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classroom.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_schedule_id"],
            ["schedule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fist_occurrence_id"],
            ["occurrence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_occurrence_id"],
            ["occurrence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_schedule_id"],
            ["schedule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fist_occurrence_id",
            "second_occurrence_id",
            "first_schedule_id",
            "second_schedule_id",
            name="unique_conflict_schedule_occurrence_tuple",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conflict")
    # ### end Alembic commands ###
