"""Update calendar and category constraints

Revision ID: 98e28ed3304b
Revises: 80b726fb19b9
Create Date: 2025-05-22 14:36:15.404397

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "98e28ed3304b"
down_revision: str | None = "80b726fb19b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_calendar_name", table_name="calendar")
    op.create_unique_constraint(
        "unique_calendar_name_for_year", "calendar", ["name", "year"]
    )
    op.drop_index("ix_holidaycategory_name", table_name="holidaycategory")
    op.create_unique_constraint(
        "unique_holiday_category_name_for_year", "holidaycategory", ["name", "year"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_holiday_category_name_for_year", "holidaycategory", type_="unique"
    )
    op.create_index("ix_holidaycategory_name", "holidaycategory", ["name"], unique=True)
    op.drop_constraint("unique_calendar_name_for_year", "calendar", type_="unique")
    op.create_index("ix_calendar_name", "calendar", ["name"], unique=True)
    # ### end Alembic commands ###
