"""Allocation Log feature

Revision ID: 9a116629041b
Revises: 05154ca469fb
Create Date: 2025-03-12 20:43:19.701373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9a116629041b"
down_revision: Union[str, None] = "05154ca469fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocationlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modified_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("ALLOCATE", "DEALLOCATE", name="actiontype"),
            nullable=False,
        ),
        sa.Column("old_classroom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("old_building", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("new_classroom", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("new_building", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "calendarholidaycategorylink_holiday_category_id_fkey",
        "calendarholidaycategorylink",
        type_="foreignkey",
    )
    op.drop_constraint(
        "calendarholidaycategorylink_calendar_id_fkey",
        "calendarholidaycategorylink",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "calendarholidaycategorylink",
        "holidaycategory",
        ["holiday_category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "calendarholidaycategorylink",
        "calendar",
        ["calendar_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "classcalendarlink_calendar_id_fkey", "classcalendarlink", type_="foreignkey"
    )
    op.drop_constraint(
        "classcalendarlink_class_id_fkey", "classcalendarlink", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "classcalendarlink",
        "calendar",
        ["calendar_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "classcalendarlink", "class", ["class_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "forumpostreactslink_mobile_user_id_fkey",
        "forumpostreactslink",
        type_="foreignkey",
    )
    op.drop_constraint(
        "forumpostreactslink_forum_post_id_fkey",
        "forumpostreactslink",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "forumpostreactslink",
        "forumpost",
        ["forum_post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "forumpostreactslink",
        "mobileuser",
        ["mobile_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "forumpostreportlink_mobile_user_id_fkey",
        "forumpostreportlink",
        type_="foreignkey",
    )
    op.drop_constraint(
        "forumpostreportlink_forum_post_id_fkey",
        "forumpostreportlink",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "forumpostreportlink",
        "mobileuser",
        ["mobile_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "forumpostreportlink",
        "forumpost",
        ["forum_post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "subjectbuildinglink_subject_id_fkey", "subjectbuildinglink", type_="foreignkey"
    )
    op.drop_constraint(
        "subjectbuildinglink_building_id_fkey",
        "subjectbuildinglink",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "subjectbuildinglink",
        "building",
        ["building_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "subjectbuildinglink",
        "subject",
        ["subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "userbuildinglink_user_id_fkey", "userbuildinglink", type_="foreignkey"
    )
    op.drop_constraint(
        "userbuildinglink_building_id_fkey", "userbuildinglink", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "userbuildinglink",
        "building",
        ["building_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "userbuildinglink", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userbuildinglink", type_="foreignkey")
    op.drop_constraint(None, "userbuildinglink", type_="foreignkey")
    op.create_foreign_key(
        "userbuildinglink_building_id_fkey",
        "userbuildinglink",
        "building",
        ["building_id"],
        ["id"],
    )
    op.create_foreign_key(
        "userbuildinglink_user_id_fkey", "userbuildinglink", "user", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "subjectbuildinglink", type_="foreignkey")
    op.drop_constraint(None, "subjectbuildinglink", type_="foreignkey")
    op.create_foreign_key(
        "subjectbuildinglink_building_id_fkey",
        "subjectbuildinglink",
        "building",
        ["building_id"],
        ["id"],
    )
    op.create_foreign_key(
        "subjectbuildinglink_subject_id_fkey",
        "subjectbuildinglink",
        "subject",
        ["subject_id"],
        ["id"],
    )
    op.drop_constraint(None, "forumpostreportlink", type_="foreignkey")
    op.drop_constraint(None, "forumpostreportlink", type_="foreignkey")
    op.create_foreign_key(
        "forumpostreportlink_forum_post_id_fkey",
        "forumpostreportlink",
        "forumpost",
        ["forum_post_id"],
        ["id"],
    )
    op.create_foreign_key(
        "forumpostreportlink_mobile_user_id_fkey",
        "forumpostreportlink",
        "mobileuser",
        ["mobile_user_id"],
        ["id"],
    )
    op.drop_constraint(None, "forumpostreactslink", type_="foreignkey")
    op.drop_constraint(None, "forumpostreactslink", type_="foreignkey")
    op.create_foreign_key(
        "forumpostreactslink_forum_post_id_fkey",
        "forumpostreactslink",
        "forumpost",
        ["forum_post_id"],
        ["id"],
    )
    op.create_foreign_key(
        "forumpostreactslink_mobile_user_id_fkey",
        "forumpostreactslink",
        "mobileuser",
        ["mobile_user_id"],
        ["id"],
    )
    op.drop_constraint(None, "classcalendarlink", type_="foreignkey")
    op.drop_constraint(None, "classcalendarlink", type_="foreignkey")
    op.create_foreign_key(
        "classcalendarlink_class_id_fkey",
        "classcalendarlink",
        "class",
        ["class_id"],
        ["id"],
    )
    op.create_foreign_key(
        "classcalendarlink_calendar_id_fkey",
        "classcalendarlink",
        "calendar",
        ["calendar_id"],
        ["id"],
    )
    op.drop_constraint(None, "calendarholidaycategorylink", type_="foreignkey")
    op.drop_constraint(None, "calendarholidaycategorylink", type_="foreignkey")
    op.create_foreign_key(
        "calendarholidaycategorylink_calendar_id_fkey",
        "calendarholidaycategorylink",
        "calendar",
        ["calendar_id"],
        ["id"],
    )
    op.create_foreign_key(
        "calendarholidaycategorylink_holiday_category_id_fkey",
        "calendarholidaycategorylink",
        "holidaycategory",
        ["holiday_category_id"],
        ["id"],
    )
    op.drop_table("allocationlog")
    # ### end Alembic commands ###
