"""Add building to group

Revision ID: a572377bd0c6
Revises: 24c87e94bf2a
Create Date: 2025-04-30 20:50:48.921709

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a572377bd0c6"
down_revision: str | None = "24c87e94bf2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("building_id", sa.Integer(), nullable=False))
    op.add_column(
        "group", sa.Column("complete", sa.Boolean(), nullable=False, default=False)
    )
    op.create_foreign_key(None, "group", "building", ["building_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_column("group", "complete")
    op.drop_column("group", "building_id")
    # ### end Alembic commands ###
