"""Update granted_by at permissions tables

Revision ID: aed010156c3c
Revises: b2f7d1c0a6e3
Create Date: 2026-05-27 21:50:49.973936

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aed010156c3c"
down_revision: str | None = "b2f7d1c0a6e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove FK constraints before renaming columns
    op.drop_constraint(
        op.f("classroompermission_granted_by_fkey"),
        "classroompermission",
        type_="foreignkey",
    )
    # Rename columns
    op.alter_column(
        "classroompermission",
        "granted_by",
        new_column_name="granted_by_id",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    # Recreate FK constraints with new column names
    op.create_foreign_key(
        op.f("classroompermission_granted_by_id_fkey"),
        "classroompermission",
        "user",
        ["granted_by_id"],
        ["id"],
    )

    # Same for course permissions
    op.drop_constraint(
        op.f("coursepermission_granted_by_fkey"), "coursepermission", type_="foreignkey"
    )
    op.alter_column(
        "coursepermission",
        "granted_by",
        new_column_name="granted_by_id",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("coursepermission_granted_by_id_fkey"),
        "coursepermission",
        "user",
        ["granted_by_id"],
        ["id"],
    )

    # Same for user roles
    op.drop_constraint(op.f("userrole_granted_by_fkey"), "userrole", type_="foreignkey")
    op.alter_column(
        "userrole",
        "granted_by",
        new_column_name="granted_by_id",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("userrole_granted_by_id_fkey"),
        "userrole",
        "user",
        ["granted_by_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("userrole_granted_by_id_fkey"), "userrole", type_="foreignkey"
    )
    op.alter_column(
        "userrole",
        "granted_by_id",
        new_column_name="granted_by",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("userrole_granted_by_fkey"), "userrole", "user", ["granted_by"], ["id"]
    )
    op.drop_constraint(
        op.f("coursepermission_granted_by_id_fkey"),
        "coursepermission",
        type_="foreignkey",
    )
    op.alter_column(
        "coursepermission",
        "granted_by_id",
        new_column_name="granted_by",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("coursepermission_granted_by_fkey"),
        "coursepermission",
        "user",
        ["granted_by"],
        ["id"],
    )
    op.drop_constraint(
        op.f("classroompermission_granted_by_id_fkey"),
        "classroompermission",
        type_="foreignkey",
    )
    op.alter_column(
        "classroompermission",
        "granted_by_id",
        new_column_name="granted_by",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        op.f("classroompermission_granted_by_fkey"),
        "classroompermission",
        "user",
        ["granted_by"],
        ["id"],
    )
    # ### end Alembic commands ###
