"""Create building permission

Revision ID: bc62ed983810
Revises: c8c2b1d4f0a1
Create Date: 2026-06-02 19:39:38.413553

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc62ed983810"
down_revision: str | None = "c8c2b1d4f0a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildingpermission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.Column("granted_by_id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column(
            "actions",
            postgresql.ARRAY(
                sa.Enum("CREATE", "READ", "UPDATE", "DELETE", name="buildingaction")
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["building.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "building_id",
            "user_id",
            "role_id",
            name="unique_permission_per_building_target",
        ),
    )
    op.create_index(
        "unique_permission_per_building_role",
        "buildingpermission",
        ["building_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("role_id IS NOT NULL"),
    )
    op.create_index(
        "unique_permission_per_building_user",
        "buildingpermission",
        ["building_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_permission_per_building_user",
        table_name="buildingpermission",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "unique_permission_per_building_role",
        table_name="buildingpermission",
        postgresql_where=sa.text("role_id IS NOT NULL"),
    )
    op.drop_table("buildingpermission")
    # ### end Alembic commands ###
