"""Remove Reservation Constraint

Revision ID: bf27d37bbe93
Revises: 9abf3e835628
Create Date: 2024-09-09 20:11:35.019116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bf27d37bbe93"
down_revision: Union[str, None] = "9abf3e835628"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_reservation_name_for_classroom", "reservation", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_reservation_name_for_classroom", "reservation", ["name", "classroom_id"]
    )
    # ### end Alembic commands ###
