"""add course options table

Revision ID: bf8387c71371
Revises: c74d94f2efe9
Create Date: 2026-05-11 18:47:45.159873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf8387c71371'
down_revision: Union[str, None] = 'c74d94f2efe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseoptions',
    sa.Column('codcur', sa.Integer(), nullable=False),
    sa.Column('codhab', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('codcur', 'codhab')
    )
    # Raw SQL (IF NOT EXISTS) instead of op.create_index: the role-based-permissions
    # branch (8ad31ffaac16_create_role_based_permissions.py) independently creates
    # these same two indexes, so a straight create collides once both branches are
    # merged into one history.
    op.execute(
        'CREATE INDEX IF NOT EXISTS ix_userabsence_schedule_id '
        'ON userabsence (schedule_id)'
    )
    op.execute(
        'CREATE INDEX IF NOT EXISTS ix_userabsence_user_schedule_id '
        'ON userabsence (user_schedule_id)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_userabsence_user_schedule_id")
    op.execute("DROP INDEX IF EXISTS ix_userabsence_schedule_id")
    op.drop_table('courseoptions')
    # ### end Alembic commands ###
