"""add course options table

Revision ID: bf8387c71371
Revises: c74d94f2efe9
Create Date: 2026-05-11 18:47:45.159873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf8387c71371'
down_revision: Union[str, None] = 'c74d94f2efe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseoptions',
    sa.Column('codcur', sa.Integer(), nullable=False),
    sa.Column('codhab', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('codcur', 'codhab')
    )
    op.create_index(op.f('ix_userabsence_schedule_id'), 'userabsence', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_userabsence_user_schedule_id'), 'userabsence', ['user_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userabsence_user_schedule_id'), table_name='userabsence')
    op.drop_index(op.f('ix_userabsence_schedule_id'), table_name='userabsence')
    op.drop_table('courseoptions')
    # ### end Alembic commands ###
