"""Add required classroom field in solicitation

Revision ID: c7c175df4791
Revises: 54e3d0a077de
Create Date: 2024-10-05 20:38:07.659472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c7c175df4791"
down_revision: Union[str, None] = "54e3d0a077de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "classroomsolicitation",
        sa.Column("required_classroom", sa.Boolean(), nullable=True),
    )
    op.execute(
        "UPDATE classroomsolicitation SET required_classroom = FALSE WHERE required_classroom IS NULL"
    )
    op.alter_column("classroomsolicitation", "required_classroom", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classroomsolicitation", "required_classroom")
    # ### end Alembic commands ###
