"""forum post created at as datetime and subject id 

Revision ID: d2f9077dbae0
Revises: 2a4d06849f24
Create Date: 2024-07-31 21:12:07.806625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2f9077dbae0'
down_revision: Union[str, None] = '2a4d06849f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
