"""Added_like_feature

Revision ID: d4cdecd00183
Revises: 5fc1e85f84a3
Create Date: 2024-10-11 17:35:27.491045

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d4cdecd00183"
down_revision: str | None = "5fc1e85f84a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forumpostreactslink",
        sa.Column("forum_post_id", sa.Integer(), nullable=False),
        sa.Column("mobile_user_id", sa.Integer(), nullable=False),
        sa.Column("post_like", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forum_post_id"],
            ["forumpost.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mobile_user_id"],
            ["mobileuser.id"],
        ),
        sa.PrimaryKeyConstraint("forum_post_id", "mobile_user_id"),
    )
    op.add_column("forumpost", sa.Column("likes_count", sa.Integer(), nullable=True))
    op.alter_column("forumpost", "enabled", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("forumpost", "enabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("forumpost", "likes_count")
    op.drop_table("forumpostreactslink")
    # ### end Alembic commands ###
