"""Make Reservation unique constraint

Revision ID: dd138282c511
Revises: cf5b3012c7f4
Create Date: 2024-07-22 11:59:16.324113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd138282c511'
down_revision: Union[str, None] = 'cf5b3012c7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_reservation_name_for_classroom', 'reservation', ['name', 'classroom_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_reservation_name_for_classroom', 'reservation', type_='unique')
    # ### end Alembic commands ###
