"""Add index to start_date and end_date for some tables

Revision ID: eb2a5824dbb3
Revises: b9a185bf09f9
Create Date: 2025-11-13 22:13:40.962915

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "eb2a5824dbb3"
down_revision: str | None = "b9a185bf09f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_class_end_date"), "class", ["end_date"], unique=False)
    op.create_index(op.f("ix_class_start_date"), "class", ["start_date"], unique=False)
    op.create_index(op.f("ix_occurrence_date"), "occurrence", ["date"], unique=False)
    op.create_index(
        op.f("ix_schedule_end_date"), "schedule", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_start_date"), "schedule", ["start_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedule_start_date"), table_name="schedule")
    op.drop_index(op.f("ix_schedule_end_date"), table_name="schedule")
    op.drop_index(op.f("ix_occurrence_date"), table_name="occurrence")
    op.drop_index(op.f("ix_class_start_date"), table_name="class")
    op.drop_index(op.f("ix_class_end_date"), table_name="class")
    # ### end Alembic commands ###
