"""connect curriculum with user

Revision ID: f1df976650ac
Revises: 4ffffa437549
Create Date: 2026-02-21 20:47:49.389497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1df976650ac'
down_revision: Union[str, None] = '4ffffa437549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('curriculum_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_curriculum_id_fkey', 'user', 'curriculum', ['curriculum_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_curriculum_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'curriculum_id')
    # ### end Alembic commands ###
