"""Add date field to Classroom Solicitation

Revision ID: f6ee6f6a6ef5
Revises: 884e87702934
Create Date: 2024-09-05 08:54:51.340501

"""

from typing import Sequence, Union
from datetime import date

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f6ee6f6a6ef5"
down_revision: Union[str, None] = "884e87702934"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("classroomsolicitation", sa.Column("date", sa.Date(), nullable=True))
    # ### end Alembic commands ###
    today = date.today()
    op.execute(
        sa.sql.text(
            f"UPDATE classroomsolicitation SET date = '{today}' WHERE date IS NULL"
        )
    )
    op.alter_column(
        "classroomsolicitation", "date", existing_type=sa.Date(), nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classroomsolicitation", "date")
    # ### end Alembic commands ###
