"""updateforumpost

Revision ID: fc16b40c7cc7
Revises: 5fefe79e8584
Create Date: 2024-07-27 16:19:24.255000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc16b40c7cc7'
down_revision: Union[str, None] = '5fefe79e8584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forumpost', sa.Column('report_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forumpost', 'report_count')
    # ### end Alembic commands ###
