"""fix classroom occurrence 2

Revision ID: ffa75055db23
Revises: a6acfa934d23
Create Date: 2024-06-18 09:36:08.006559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffa75055db23'
down_revision: Union[str, None] = 'a6acfa934d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('occurrence', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('occurrence', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_occurrence_schedule_id', table_name='occurrence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_occurrence_schedule_id', 'occurrence', ['schedule_id'], unique=False)
    op.alter_column('occurrence', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('occurrence', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
