name: Deploy Prod
on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy backend to prod
    runs-on: ubuntu-latest
    steps:
    - name: deploying backend to prod internuvem machine
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 200.144.244.245
        username: ubuntu
        password: UHtX8Tw9e
        port: 2222
        script: ./start_uspolis_back.sh