"""Runs the test suite and rewrites the "Current metrics" table in TESTS.md.

Usage: poetry run python tests/scripts/update_test_metrics.py

Only the block between the `<!-- METRICS:START -->`/`<!-- METRICS:END -->`
markers in TESTS.md is replaced; everything else in the file is left as-is.
"""

import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
TESTS_DIR = REPO_ROOT / "tests"
TESTS_MD = REPO_ROOT / "TESTS.md"
COVERAGE_JSON = REPO_ROOT / "coverage.json"

TEST_FUNC_RE = re.compile(r"^\s*(?:async\s+)?def (test_\w+)", re.MULTILINE)

METRICS_BLOCK_RE = re.compile(
    r"<!-- METRICS:START -->.*?<!-- METRICS:END -->", re.DOTALL
)


def count_test_files() -> int:
    return len(list(TESTS_DIR.rglob("test_*.py")))


def count_test_functions() -> int:
    total = 0
    for path in TESTS_DIR.rglob("test_*.py"):
        total += len(TEST_FUNC_RE.findall(path.read_text(encoding="utf-8")))
    return total


def dedicated_test_file_ratio(source_dirs: list[Path]) -> tuple[int, int, list[str]]:
    """How many *.py files across source_dirs have a matching test_<name>.py
    somewhere under tests/ (a "dedicated" test file, by exact name match)."""
    names = sorted(
        p.stem
        for source_dir in source_dirs
        for p in source_dir.glob("*.py")
        if p.stem != "__init__"
    )
    tested = [name for name in names if list(TESTS_DIR.rglob(f"test_{name}.py"))]
    return len(tested), len(names), tested


def run_pytest() -> str:
    result = subprocess.run(
        ["poetry", "run", "pytest", "--cov-report=json", "-q"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    return result.stdout + result.stderr


def parse_summary(output: str) -> dict[str, int]:
    counts: dict[str, int] = {"passed": 0, "failed": 0, "deselected": 0}
    for key in ("passed", "failed", "deselected", "skipped", "xfailed", "xpassed"):
        match = re.search(rf"(\d+) {key}\b", output)
        if match:
            counts[key] = int(match.group(1))
    match = re.search(r"(\d+) errors?\b", output)
    if match:
        counts["errors"] = int(match.group(1))
    return counts


def parse_coverage() -> dict[str, float | int]:
    if not COVERAGE_JSON.exists():
        raise RuntimeError(
            f"{COVERAGE_JSON} was not written — did the pytest run above fail "
            "before collecting coverage?"
        )
    data = json.loads(COVERAGE_JSON.read_text(encoding="utf-8"))
    return data["totals"]  # type: ignore[no-any-return]


def render_table(
    test_files: int,
    test_functions: int,
    totals: dict[str, float | int],
    repo_tested: int,
    repo_total: int,
    service_tested: int,
    service_total: int,
    summary: dict[str, int],
) -> str:
    line_pct = totals["percent_statements_covered"]
    branch_pct = totals["percent_branches_covered"]
    combined_pct = totals["percent_covered"]
    stmts = totals["num_statements"]
    missed_stmts = totals["missing_lines"]
    branches = totals["num_branches"]
    missed_branches = totals["missing_branches"]
    partial_branches = totals["num_partial_branches"]

    extra_summary_bits = []
    for key in ("skipped", "xfailed", "xpassed", "errors"):
        if summary.get(key):
            extra_summary_bits.append(f"{summary[key]} {key}")
    summary_line = f"{summary['passed']} passed, {summary['failed']} failed, {summary['deselected']} deselected"
    if extra_summary_bits:
        summary_line += ", " + ", ".join(extra_summary_bits)

    rows = [
        ("Test files", str(test_files)),
        ("Test functions", str(test_functions)),
        (
            "Line coverage",
            f"{line_pct:.2f}% ({stmts:,} statements, {missed_stmts:,} missed)",
        ),
        (
            "Branch coverage",
            f"{branch_pct:.2f}% ({branches:,} branches, {missed_branches:,} fully "
            f"missed, {partial_branches:,} partial)",
        ),
        ("Combined coverage (line + branch)", f"{combined_pct:.2f}%"),
        ("Repository test-file ratio", f"{repo_tested} / {repo_total}"),
        ("Service test-file ratio", f"{service_tested} / {service_total}"),
        ("Last full run", summary_line),
    ]

    table_lines = ["| Metric | Value |", "|---|---|"]
    table_lines += [f"| {label} | {value} |" for label, value in rows]

    return "\n".join(
        [
            "<!-- METRICS:START -->",
            "<!-- Auto-generated by tests/scripts/update_test_metrics.py — do not "
            "hand-edit",
            "     the table below; edit the script instead. Everything outside the",
            "     METRICS:START/END markers is untouched by the script. -->",
            "",
            f"Baseline as of **{date.today().isoformat()}**.",
            "",
            *table_lines,
            "",
            "The failure/skip counts above are whatever the run produced — check "
            "§7 to see which ones are pre-existing/known issues versus new "
            "regressions.",
            "<!-- METRICS:END -->",
        ]
    )


def update_tests_md(new_block: str) -> None:
    content = TESTS_MD.read_text(encoding="utf-8")
    if not METRICS_BLOCK_RE.search(content):
        raise RuntimeError(
            "Could not find METRICS:START/METRICS:END markers in TESTS.md — "
            "has the file been restructured?"
        )
    updated = METRICS_BLOCK_RE.sub(new_block.replace("\\", "\\\\"), content)
    TESTS_MD.write_text(updated, encoding="utf-8")


def main() -> None:
    print("Running the test suite (this can take a while)...", file=sys.stderr)
    output = run_pytest()
    print(output, file=sys.stderr)

    summary = parse_summary(output)
    totals = parse_coverage()
    test_files = count_test_files()
    test_functions = count_test_functions()
    repo_tested, repo_total, _ = dedicated_test_file_ratio(
        [REPO_ROOT / "server" / "repositories"]
    )
    service_tested, service_total, _ = dedicated_test_file_ratio(
        [
            REPO_ROOT / "server" / "services",
            REPO_ROOT / "server" / "services" / "security",
        ]
    )

    new_block = render_table(
        test_files=test_files,
        test_functions=test_functions,
        totals=totals,
        repo_tested=repo_tested,
        repo_total=repo_total,
        service_tested=service_tested,
        service_total=service_total,
        summary=summary,
    )
    update_tests_md(new_block)
    print(f"Updated {TESTS_MD} with fresh metrics.", file=sys.stderr)


if __name__ == "__main__":
    main()
